name: flutter_file_utils
description: Helper tools for managing files on Android
version: 0.1.1+5
homepage: https://github.com/kw2019ltd/flutter_file_utils

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.7.0
  path_provider: ^1.6.24
  package_info: ^0.4.3+2

dev_dependencies:
  pedantic: ^1.9.2

flutter:

